### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by hhslepicka** [zylan29/pydm#1]
I would like to know if this project is still under development or if you consider it to be over?
I am asking as we have a project with the same name (https://github.com/slaclab/pydm) and I am interested in using the pypi name if you are no longer planning on create new releases and develop your project.
We currently ship our package using Anaconda, having the ability to also distribute it via pypi would be great for us.

**Comment by zylan29** [comment]
I have already deleted my pydm package from pypi. 

Will mark this issue as closed.
